name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install MinGW
      run: |
        choco install mingw -y
        echo "C:\ProgramData\chocolatey\bin" >> $GITHUB_PATH

    - name: Build Executable using Makefile
      run: |
        make all

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: c2export_singlethr
        path: bin/c2export_singlethr.exe 
    - name: Upload Executable 2
      uses: actions/upload-artifact@v4
      with:
        name: c2export_multithr
        path: bin/c2export_multithr.exe
      

