name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install MinGW
      run: |
        choco install mingw -y
        echo "C:\ProgramData\chocolatey\bin" >> $GITHUB_PATH

    - name: Ensure bin directory exists
      run: mkdir -p bin
      
    - name: Build Executable using Makefile
      run: make -B

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: c2export_dl
        path: bin/c2export_dl.exe  # Correct path

